authors: []
build_space: build
buildlist: []
catkin_make_args: []
cmake_args: []
devel_layout: linked
devel_space: devel
extend_path: null
extends: null
install: false
install_space: install
isolate_install: false
jobs_args: []
licenses:
- TODO
log_space: logs
maintainers: []
make_args: []
skiplist: []
source_space: src
use_env_cache: false
use_internal_make_jobserver: true
