// Generated by gencpp from file distance_msgs/conversion.msg
// DO NOT EDIT!


#ifndef DISTANCE_MSGS_MESSAGE_CONVERSION_H
#define DISTANCE_MSGS_MESSAGE_CONVERSION_H

#include <ros/service_traits.h>


#include <distance_msgs/conversionRequest.h>
#include <distance_msgs/conversionResponse.h>


namespace distance_msgs
{

struct conversion
{

typedef conversionRequest Request;
typedef conversionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct conversion
} // namespace distance_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::distance_msgs::conversion > {
  static const char* value()
  {
    return "7bda023e35ef66c372a0d64f03917b2f";
  }

  static const char* value(const ::distance_msgs::conversion&) { return value(); }
};

template<>
struct DataType< ::distance_msgs::conversion > {
  static const char* value()
  {
    return "distance_msgs/conversion";
  }

  static const char* value(const ::distance_msgs::conversion&) { return value(); }
};


// service_traits::MD5Sum< ::distance_msgs::conversionRequest> should match
// service_traits::MD5Sum< ::distance_msgs::conversion >
template<>
struct MD5Sum< ::distance_msgs::conversionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::distance_msgs::conversion >::value();
  }
  static const char* value(const ::distance_msgs::conversionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::distance_msgs::conversionRequest> should match
// service_traits::DataType< ::distance_msgs::conversion >
template<>
struct DataType< ::distance_msgs::conversionRequest>
{
  static const char* value()
  {
    return DataType< ::distance_msgs::conversion >::value();
  }
  static const char* value(const ::distance_msgs::conversionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::distance_msgs::conversionResponse> should match
// service_traits::MD5Sum< ::distance_msgs::conversion >
template<>
struct MD5Sum< ::distance_msgs::conversionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::distance_msgs::conversion >::value();
  }
  static const char* value(const ::distance_msgs::conversionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::distance_msgs::conversionResponse> should match
// service_traits::DataType< ::distance_msgs::conversion >
template<>
struct DataType< ::distance_msgs::conversionResponse>
{
  static const char* value()
  {
    return DataType< ::distance_msgs::conversion >::value();
  }
  static const char* value(const ::distance_msgs::conversionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DISTANCE_MSGS_MESSAGE_CONVERSION_H
