// Generated by gencpp from file distance_msgs/conversionRequest.msg
// DO NOT EDIT!


#ifndef DISTANCE_MSGS_MESSAGE_CONVERSIONREQUEST_H
#define DISTANCE_MSGS_MESSAGE_CONVERSIONREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace distance_msgs
{
template <class ContainerAllocator>
struct conversionRequest_
{
  typedef conversionRequest_<ContainerAllocator> Type;

  conversionRequest_()
    : a(0)  {
    }
  conversionRequest_(const ContainerAllocator& _alloc)
    : a(0)  {
  (void)_alloc;
    }



   typedef int32_t _a_type;
  _a_type a;





  typedef boost::shared_ptr< ::distance_msgs::conversionRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::distance_msgs::conversionRequest_<ContainerAllocator> const> ConstPtr;

}; // struct conversionRequest_

typedef ::distance_msgs::conversionRequest_<std::allocator<void> > conversionRequest;

typedef boost::shared_ptr< ::distance_msgs::conversionRequest > conversionRequestPtr;
typedef boost::shared_ptr< ::distance_msgs::conversionRequest const> conversionRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::distance_msgs::conversionRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::distance_msgs::conversionRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::distance_msgs::conversionRequest_<ContainerAllocator1> & lhs, const ::distance_msgs::conversionRequest_<ContainerAllocator2> & rhs)
{
  return lhs.a == rhs.a;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::distance_msgs::conversionRequest_<ContainerAllocator1> & lhs, const ::distance_msgs::conversionRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace distance_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::distance_msgs::conversionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::distance_msgs::conversionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::distance_msgs::conversionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::distance_msgs::conversionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::distance_msgs::conversionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::distance_msgs::conversionRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::distance_msgs::conversionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5c9fb1a886e81e3162a5c87bf55c072b";
  }

  static const char* value(const ::distance_msgs::conversionRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5c9fb1a886e81e31ULL;
  static const uint64_t static_value2 = 0x62a5c87bf55c072bULL;
};

template<class ContainerAllocator>
struct DataType< ::distance_msgs::conversionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "distance_msgs/conversionRequest";
  }

  static const char* value(const ::distance_msgs::conversionRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::distance_msgs::conversionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 a\n"
;
  }

  static const char* value(const ::distance_msgs::conversionRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::distance_msgs::conversionRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.a);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct conversionRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::distance_msgs::conversionRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::distance_msgs::conversionRequest_<ContainerAllocator>& v)
  {
    s << indent << "a: ";
    Printer<int32_t>::stream(s, indent + "  ", v.a);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DISTANCE_MSGS_MESSAGE_CONVERSIONREQUEST_H
