// Generated by gencpp from file distance_msgs/dist_info.msg
// DO NOT EDIT!


#ifndef DISTANCE_MSGS_MESSAGE_DIST_INFO_H
#define DISTANCE_MSGS_MESSAGE_DIST_INFO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <sensor_msgs/Range.h>

namespace distance_msgs
{
template <class ContainerAllocator>
struct dist_info_
{
  typedef dist_info_<ContainerAllocator> Type;

  dist_info_()
    : dist()
    , mno(0)
    , mname()  {
    }
  dist_info_(const ContainerAllocator& _alloc)
    : dist(_alloc)
    , mno(0)
    , mname(_alloc)  {
  (void)_alloc;
    }



   typedef  ::sensor_msgs::Range_<ContainerAllocator>  _dist_type;
  _dist_type dist;

   typedef int32_t _mno_type;
  _mno_type mno;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _mname_type;
  _mname_type mname;





  typedef boost::shared_ptr< ::distance_msgs::dist_info_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::distance_msgs::dist_info_<ContainerAllocator> const> ConstPtr;

}; // struct dist_info_

typedef ::distance_msgs::dist_info_<std::allocator<void> > dist_info;

typedef boost::shared_ptr< ::distance_msgs::dist_info > dist_infoPtr;
typedef boost::shared_ptr< ::distance_msgs::dist_info const> dist_infoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::distance_msgs::dist_info_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::distance_msgs::dist_info_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::distance_msgs::dist_info_<ContainerAllocator1> & lhs, const ::distance_msgs::dist_info_<ContainerAllocator2> & rhs)
{
  return lhs.dist == rhs.dist &&
    lhs.mno == rhs.mno &&
    lhs.mname == rhs.mname;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::distance_msgs::dist_info_<ContainerAllocator1> & lhs, const ::distance_msgs::dist_info_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace distance_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::distance_msgs::dist_info_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::distance_msgs::dist_info_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::distance_msgs::dist_info_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::distance_msgs::dist_info_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::distance_msgs::dist_info_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::distance_msgs::dist_info_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::distance_msgs::dist_info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9437189fa374886e3521594bcfcd5828";
  }

  static const char* value(const ::distance_msgs::dist_info_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9437189fa374886eULL;
  static const uint64_t static_value2 = 0x3521594bcfcd5828ULL;
};

template<class ContainerAllocator>
struct DataType< ::distance_msgs::dist_info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "distance_msgs/dist_info";
  }

  static const char* value(const ::distance_msgs::dist_info_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::distance_msgs::dist_info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sensor_msgs/Range dist\n"
"int32 mno\n"
"string mname\n"
"================================================================================\n"
"MSG: sensor_msgs/Range\n"
"# Single range reading from an active ranger that emits energy and reports\n"
"# one range reading that is valid along an arc at the distance measured. \n"
"# This message is  not appropriate for laser scanners. See the LaserScan\n"
"# message if you are working with a laser scanner.\n"
"\n"
"# This message also can represent a fixed-distance (binary) ranger.  This\n"
"# sensor will have min_range===max_range===distance of detection.\n"
"# These sensors follow REP 117 and will output -Inf if the object is detected\n"
"# and +Inf if the object is outside of the detection range.\n"
"\n"
"Header header           # timestamp in the header is the time the ranger\n"
"                        # returned the distance reading\n"
"\n"
"# Radiation type enums\n"
"# If you want a value added to this list, send an email to the ros-users list\n"
"uint8 ULTRASOUND=0\n"
"uint8 INFRARED=1\n"
"\n"
"uint8 radiation_type    # the type of radiation used by the sensor\n"
"                        # (sound, IR, etc) [enum]\n"
"\n"
"float32 field_of_view   # the size of the arc that the distance reading is\n"
"                        # valid for [rad]\n"
"                        # the object causing the range reading may have\n"
"                        # been anywhere within -field_of_view/2 and\n"
"                        # field_of_view/2 at the measured range. \n"
"                        # 0 angle corresponds to the x-axis of the sensor.\n"
"\n"
"float32 min_range       # minimum range value [m]\n"
"float32 max_range       # maximum range value [m]\n"
"                        # Fixed distance rangers require min_range==max_range\n"
"\n"
"float32 range           # range data [m]\n"
"                        # (Note: values < range_min or > range_max\n"
"                        # should be discarded)\n"
"                        # Fixed distance rangers only output -Inf or +Inf.\n"
"                        # -Inf represents a detection within fixed distance.\n"
"                        # (Detection too close to the sensor to quantify)\n"
"                        # +Inf represents no detection within the fixed distance.\n"
"                        # (Object out of range)\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::distance_msgs::dist_info_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::distance_msgs::dist_info_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.dist);
      stream.next(m.mno);
      stream.next(m.mname);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct dist_info_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::distance_msgs::dist_info_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::distance_msgs::dist_info_<ContainerAllocator>& v)
  {
    s << indent << "dist: ";
    s << std::endl;
    Printer< ::sensor_msgs::Range_<ContainerAllocator> >::stream(s, indent + "  ", v.dist);
    s << indent << "mno: ";
    Printer<int32_t>::stream(s, indent + "  ", v.mno);
    s << indent << "mname: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.mname);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DISTANCE_MSGS_MESSAGE_DIST_INFO_H
